function [fitresult, gof] = casson(x, mu_wall)
%CREATEFIT(X,MU_WALL)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input: x
%      Y Output: mu_wall
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Dec-2022 16:28:23


%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( x, mu_wall );

% Set up fittype and options.
ft = fittype( 'kc+ty/gamma+2*sqrt(kc*ty/gamma)', 'independent', 'gamma', 'dependent', 'mu_wall' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.934010684229183 0.12990620847373];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 2' );
h = plot( fitresult, xData, yData );
legend( h, 'mu_wall vs. x', 'untitled fit 2', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'mu_wall', 'Interpreter', 'none' );
grid on


