function [fitresult, gof] = power_law(x, mu_wall)
%CREATEFIT(X,MU_WALL)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input: x
%      Y Output: mu_wall
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Dec-2022 16:13:51


%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( x, mu_wall );

% Set up fittype and options.
ft = fittype( 'kp*x^(n-1)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.530797553008973 0.779167230102011];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 2' );
h = plot( fitresult, xData, yData );
legend( h, 'mu_wall vs. x', 'untitled fit 2', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'mu_wall', 'Interpreter', 'none' );
grid on


